### PR TITLE
Add MadFixed32

### LINKED ISSUE #8: The format of the samples should be stronger typed or better documented
Apparently the samples produced by simplemad are in fixed point and need [a conversion step](https://github.com/bendykst/simple-mad.rs/blob/49df613de8fbd77e9712252da9d18804e7bff868/simplemad_sys/libmad-src/minimad.c#L107-L121) before being rendered.

### PR DESCRIPTION
**Pull request by bendykst**
Add MadFixed32 to resolve #8

### CODE REVIEW

**Comment by tomaka** [comment]
Ideally libmad-sys contains only the exact definitions that libmad gives you. If libmad returns a `i32`, you should return a `i32`.

Other than that, `to_f32` and `to_64` look wrong. The value of a floating point sample should be between -1.0 and 1.0, not between -8.0 and 8.0. At least that's what I expect.

And I don't understand the `to_i32`. In rodio I just rewrote the C code from `minimad.c` and it works: https://github.com/tomaka/rodio/blob/c46fbd83e430a877d55d0fdfddff06618f0059c5/src/decoder/mp3.rs#L67-L70

**Comment by bendykst** [comment]
> Ideally libmad-sys contains only the exact definitions that libmad gives you.

I think it's most accurate to say that libmad gives you samples of type `mad_fixed_t`. It's a typedef of i32, but since it's a fixed point representation, if you want an actual i32 sample, you need to do a conversion. 

`mad_fixed_t` has a range of -8.0 to 8.0. If you simply cast it to an i32, whose range is used to represent a signal from -1.0 to 1.0, the new samples will be too small by a factor of 8. That's the explanation for `to_i32`, which clips the signal and scales by 8. The same clipping and scaling can be seen in minimad's conversion to i16.

> Other than that, to_f32 and to_64 look wrong. The value of a floating point sample should be between -1.0 and 1.0, not between -8.0 and 8.0.

The same explanation applies here, but I forwent the clipping, since it feels bad to throw away information. However, on reflection, it's probably good to have a contract that every conversion from MadFixed32 yields a value between -1.0 and 1.0 (or MIN_VAL to MAX_VAL for integer representations). It's probably an academic consideration, since I don't think that libmad will ever return a value that scales beyond ±1.0, though I would have to confirm that.

**Comment by tomaka** [comment]
libmad-sys is supposed to contain only the C library and the code that allows interfacing with this library. In other words, the direct translation of the C headers into Rust.

**Comment by bendykst** [comment]
Ah, ok. So do I define the struct in *sys and put the impls in libmad

**Comment by albel727** [comment]
>According to the guidlines libmad-sys is supposed to contain only the C library and the code that allows interfacing with this library. In other words, the direct translation of the C headers into Rust.

That doesn't read to me like "typedefs to ints have to be i32", no matter how I look at it. The initial approach with `#repr(C) MadFixed32(i32)` in simplemad-sys was most appropriate, as they're not just ints, but fixed points of particular format, and C header conveys that information, while i32 in the rust code does not.

Not only that, but during "fixing" simplemad into current state, I think a bug was introduced, where `MadFixed32::from(i32)` is used to create `MadFixed32` from a decoded sample in sample buffers. 

https://github.com/bendykst/simple-mad.rs/blob/195a087fd46e5723fd26b2662a50da087c08c301/simplemad/src/lib.rs#L257

But `MadFixed32::from(i32)` divides the i32 by 8. I think the intention was to use `MadFixed32::new(i32)`, which would do nothing with the i32.

That conversion also introduces pointless `Vec` allocation per every decoded frame, when it was possible to just reinterpret original `[i32]` buffers as `&mut [MadFixed32]` and give that in `Frame`. Or at least give some provision for `Frame` reuse.

**Pull request merged**
